### ISSUE TITLE
MTV data error

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#748]
Since updating to 5.4.0, MTV upload seems to be broken (the torrent actually gets uploaded to the site, but won't get injected into the client).

```
Processing uploads to trackers.....
Traceback (most recent call last):
  File "/Upload-Assistant/src/trackers/MTV.py", line 162, in upload
    await common.add_tracker_torrent(meta, self.tracker, self.source_flag, self.config['TRACKERS'][self.tracker].get('announce_url'), str(response.url))
  File "/Upload-Assistant/src/trackers/COMMON.py", line 64, in add_tracker_torrent
    if await self.path_exists(path):
             ^^^^^^^^^^^^^^^^
AttributeError: 'COMMON' object has no attribute 'path_exists'
None
```
and after:
`MTV: data error -It may have uploaded, check manually.`
