### ISSUE TITLE
DVD upload won't work on 5.0.0

### ISSUE THREAD

**Issue by FunFrog-BY** [Audionut/Upload-Assistant#532]
```
Gathering info for REDACTED`
Error in gather_prep: get_dvd_size() missing 1 required positional argument: 'manual_dvds'
Traceback (most recent call last):
  File "C:\Soft\L4G\UA4\upload.py", line 97, in process_meta
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\L4G\UA4\src\prep.py", line 133, in gather_prep
    meta['dvd_size'] = await get_dvd_size(meta['discs'], meta.get('manual_dvds'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_dvd_size() missing 1 required positional argument: 'manual_dvds'

```
Tried both DVD5 and DVD9, several releases. None would work.

**Comment by FunFrog-BY** [comment]
And it keeps descriptions even after saying "Description discarded."

And it keeps bad images. This is from one single run of upload.py:

`
Content type is not an image: https://pixhost.to/show/26/344479570_file-upload-0.png
Content type is not an image: https://pixhost.to/show/26/344479572_file-upload-0.png
Image https://t85.pixhost.to/thumbs/26/344479570_file-upload-0.png resolution (196p) is outside the
allowed range (756-1080p). Skipping.
Content type is not an image: https://pixhost.to/show/26/344479574_file-upload-0.png
Image https://t85.pixhost.to/thumbs/26/344479572_file-upload-0.png resolution (196p) is outside the
allowed range (756-1080p). Skipping.
Content type is not an image: https://pixhost.to/show/26/344479579_file-upload-0.png
Image https://t85.pixhost.to/thumbs/26/344479574_file-upload-0.png resolution (196p) is outside the
allowed range (756-1080p). Skipping.
Image https://t85.pixhost.to/thumbs/26/344479579_file-upload-0.png resolution (196p) is outside the
allowed range (756-1080p). Skipping.
....
There are already at least 6 images in the image list. Skipping additional screenshots.
[Here upload was made to FNP with screens that didn't work.]
....
Tracker: HDB, Upload: YES
Rehosting Images...
No images found for upload
[Here upload was made to HDB without screens at all]
Tracker: MTV, Upload: YES
Reuploading images for MTV...
No valid images found for MTV, will attempt to reupload...
All capture tasks finished. Cleaning up...
Successfully captured 6 screenshots.
Now optimizing images...
Shutting down optimization workers...
Successfully optimized 6 images.
[Here upload as made to MTV with 6 good screens]
`
